import { Album } from "../../utils/types";

export const Howls: Album = {
   slug: "howls",
   title: "Howls",
   cover: "/cover/howls.jpeg",
   artist: "Shobee",
   tracks: [
      {
         title: "Howls - Intro",
         duration: 109,
         artists: ["Shobee"],
         src: "/audio/howls/Howls - Intro.mp3",
         waveform: "/audio/howls/Howls - Intro.dat",
      },
      {
         title: "Do It Again",
         duration: 165,
         artists: ["Shobee"],
         src: "/audio/howls/Do It Again.mp3",
         waveform: "/audio/howls/Do It Again.dat",
      },
      {
         title: "All I Did",
         duration: 165,
         artists: ["Shobee"],
         src: "/audio/howls/All I Did.mp3",
         waveform: "/audio/howls/All I Did.dat",
      },
      {
         title: "Ambitions",
         duration: 150,
         artists: ["Shobee"],
         src: "/audio/howls/Ambitions.mp3",
         waveform: "/audio/howls/Ambitions.dat",
      },
      {
         title: "Power",
         duration: 169,
         artists: ["Shobee"],
         src: "/audio/howls/Power.mp3",
         waveform: "/audio/howls/Power.dat",
      },
      {
         title: "Khouk - Skit",
         duration: 34,
         artists: ["Shobee"],
         src: "/audio/howls/Khouk - Skit.mp3",
         waveform: "/audio/howls/Khouk - Skit.dat",
      },
      {
         title: "Work",
         duration: 196,
         artists: ["Shobee", "Madd"],
         src: "/audio/howls/Work (feat. Madd).mp3",
         waveform: "/audio/howls/Work (feat. Madd).dat",
      },
      {
         title: "Makayn Tahed",
         duration: 227,
         artists: ["Shobee"],
         src: "/audio/howls/Makayn Tahed.mp3",
         waveform: "/audio/howls/Makayn Tahed.dat",
      },
      {
         title: "Wild Beast",
         duration: 105,
         artists: ["Shobee"],
         src: "/audio/howls/Wild Beast.mp3",
         waveform: "/audio/howls/Wild Beast.dat",
      },
      {
         title: "Sad Situation",
         duration: 185,
         artists: ["Shobee", "Lala &ce"],
         src: "/audio/howls/Sad Situation (feat. Lala &ce).mp3",
         waveform: "/audio/howls/Sad Situation (feat. Lala &ce).dat",
      },
      {
         title: "Mission",
         duration: 189,
         artists: ["Shobee"],
         src: "/audio/howls/Mission.mp3",
         waveform: "/audio/howls/Mission.dat",
      },
      {
         title: "Crown",
         duration: 123,
         artists: ["Shobee"],
         src: "/audio/howls/Crown.mp3",
         waveform: "/audio/howls/Crown.dat",
      },
      {
         title: "Committed",
         duration: 121,
         artists: ["Shobee", "Snor"],
         src: "/audio/howls/Committed (feat. Snor).mp3",
         waveform: "/audio/howls/Committed (feat. Snor).dat",
      },

      {
         title: "War - Interlude",
         duration: 67,
         artists: ["Shobee"],
         src: "/audio/howls/War - Interlude.mp3",
         waveform: "/audio/howls/War - Interlude.dat",
      },
      {
         title: "Train De Vie",
         duration: 166,
         artists: ["Shobee", "Laylow"],
         src: "/audio/howls/Train De Vie (feat. Laylow).mp3",
         waveform: "/audio/howls/Train De Vie (feat. Laylow).dat",
      },
      {
         title: "Want Some More",
         duration: 182,
         artists: ["Shobee"],
         src: "/audio/howls/Want Some More.mp3",
         waveform: "/audio/howls/Want Some More.dat",
      },
      {
         title: "Break Your Face",
         duration: 198,
         artists: ["Shobee"],
         src: "/audio/howls/Break Your Face.mp3",
         waveform: "/audio/howls/Break Your Face.dat",
      },
      {
         title: "Ungrateful",
         duration: 215,
         artists: ["Shobee"],
         src: "/audio/howls/Ungrateful.mp3",
         waveform: "/audio/howls/Ungrateful.dat",
      },
   ],
};

export default [Howls];
